---
- name: Installing prerequirements
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Arch Tasks
      block:
        - name: Arch | Installing required software
          become: yes
          pacman:
            name:
              - yay
            state: latest
            update_cache: true
        - name: Arch | Installing ansible module for yay
          git:
            repo: https://github.com/mnussbaum/ansible-yay.git
            dest: "{{ ansible_user_dir }}/.ansible/plugins/modules/yay"

